
services:
  api:
    build: .
    env_file:
      - .test.env
    ports:
      - 8008:8008
    depends_on:
      - db
    container_name: "svc-recipes"
 
  db:
    image: postgres:15-bookworm
    volumes:
      - svc_recipes_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .test.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
volumes:
    svc_recipes_postgres_data:
