
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 8008:8008
    depends_on:
      - db
 
  db:
    image: postgres:15-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
 
volumes:
    postgres_data:
